name: tests-payments

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments/src/test && touch setEnvVars.ts echo process.env.STRIPE_KEY=${{secrets.STRIPE_KEY}} >> setEnvVars.ts && cd ../../ && npm install && npm run test:ci
